# .scrutinizer.yml
before_commands:
    - composer install --dev --prefer-source --no-interaction

filter:
    paths: ["lib/*"]
    excluded_paths:
        - "app/*"
        - "bin/*"
        - "docs/*"
        - "tests/*"
        - "web/*"

tools:
    external_code_coverage:
        timeout: 600

    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: ["docs", "tests", "bin"]
    php_cpd:
        enabled: true
        excluded_dirs: ["docs", "tests", "bin"]

checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        php:
            version: 5.6
        ini:
            "date.timezone": "UTC"
