filter:
    paths: [lib/*]
    excluded_paths: [bin/*, docs/*, tests/*]
before_commands:
    - 'composer install --prefer-source'
tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [docs, tests, bin]
    php_cpd:
        enabled: true
        excluded_dirs: [docs, tests, bin]
