language: php

php:
  - 5.6
  - 7.0

sudo: true

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

before_install:
  - sudo locale-gen en_US
  - sudo locale-gen en_US.UTF-8
  - sudo locale-gen de_DE
  - sudo locale-gen de_DE.UTF-8
  - sudo dpkg-reconfigure locales
  - composer self-update --no-interaction
  - composer --version --no-interaction

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

before_script:
  - composer update --prefer-dist $PREFER_LOWEST
  - composer --optimize-autoloader --no-interaction

script:
  - bin/phpunit -c app/ --coverage-clover=coverage.clover --coverage-html=./docs/coverage

after_script:
  # We upload only for reference platform! This is our base for further code analyses and so on.
  - if [ $(phpenv version-name) == "5.6" ] && [ "$PREFER_LOWEST" == "--prefer-lowest" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $(phpenv version-name) == "5.6" ] && [ "$PREFER_LOWEST" == "--prefer-lowest" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover > /dev/null 2>&1; fi

after_success:
  # Push coverage to github pages branch
  - chmod +x ./update-gh-pages.sh
  - if [ $(phpenv version-name) == "5.6" ] && [ "$PREFER_LOWEST" == "--prefer-lowest" ]; then bash ./update-gh-pages.sh; fi
  # CREATE GIT TAG
  - git config --global user.email "builds@travis-ci.org"
  - git config --global user.name "Travis"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
  - echo -n $GIT_TAG > public/version
  - git commit -m "Set build VERSION number" public/version
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --tags --quiet https://$GITHUBKEY@github.com/clickalicious/Doozr > /dev/null 2>&1

# blacklist
branches:
  except:
    - /^build-[0-9a-z\-]*/

# Who to notify?
notifications:
  email:
    recipients:
      - opensource@clickalicious.de
    on_success: always
    on_failure: change
  slack: clickalicious:$SLACKKEY
