language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: true

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

before_install:
  - sudo locale-gen en_US
  - sudo locale-gen en_US.UTF-8
  - sudo locale-gen de_DE
  - sudo locale-gen de_DE.UTF-8
  - sudo dpkg-reconfigure locales
  - travis_retry composer selfupdate
  - composer --version

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

before_script:
  - travis_retry composer update --prefer-source $PREFER_LOWEST
  - composer --optimize-autoloader
  - mkdir -p ./build/logs
  - ls -LR

script:
  - phpunit -c tests/phpunit.xml --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token=$SCRUTINIZERKEY --format=php-clover ./build/logs/clover.xml > /dev/null 2>&1

after_success:
  # Push coverage to github pages branch
  - chmod +x ./bin/update-gh-pages.sh
  - bash ./bin/update-gh-pages.sh
  # CREATE GIT TAG
  - git config --global user.email "builds@travis-ci.org"
  - git config --global user.name "Travis"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
  - echo -n $GIT_TAG > public/version
  - git commit -m "Set build VERSION number" public/version
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --tags --quiet https://$GITHUBKEY@github.com/clickalicious/DoozR > /dev/null 2>&1

# blacklist
branches:
  except:
    - /^build-[0-9a-z\-]*/
