<?php
/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/**
 * DoozR - Doodi - CouchDB - Autoload - Map
 *
 * DoodiCouchdbAutoload.php - Autoload - Map - This array is autogenerated and topoligically sorted.
 * Do not change anything in here, but just run the following script in the trunk/ directory.
 *
 * PHP versions 5
 *
 * LICENSE:
 * DoozR - The PHP-Framework
 *
 * Copyright (c) 2005 - 2013, Benjamin Carl - All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 * - All advertising materials mentioning features or use of this software
 *   must display the following acknowledgement: This product includes software
 *   developed by Benjamin Carl and other contributors.
 * - Neither the name Benjamin Carl nor the names of other contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Please feel free to contact us via e-mail: opensource@clickalicious.de
 *
 * @category   DoozR
 * @package    DoozR_Model
 * @subpackage DoozR_Model_Doodi
 * @author     Benjamin Carl <opensource@clickalicious.de>
 * @copyright  2005 - 2013 Benjamin Carl
 * @license    http://www.opensource.org/licenses/bsd-license.php The BSD License
 * @version    Git: $Id$
 * @link       http://clickalicious.github.com/DoozR/
 * @see        -
 * @since      -
 */
return array(
    'Doodi_Couchdb_Array_Response'                => 'Array/Response/DoodiCouchdbArrayResponse.class.php',
    'Doodi_Couchdb_Connection'                    => 'Connection/DoodiCouchdbConnection.class.php',
    'Doodi_Couchdb_Custom_Connection'             => 'Custom/Connection/DoodiCouchdbCustomConnection.class.php',
    'Doodi_Couchdb_Data_Response'                 => 'Data/Response/DoodiCouchdbDataResponse.class.php',
    'Doodi_Couchdb_Document'                      => 'Document/DoodiCouchdbDocument.class.php',
    'Doodi_Couchdb_Document_Array_Validator'      => 'Document/Array/Validator/DoodiCouchdbDocumentArrayValidator.class.php',
    'Doodi_Couchdb_Group_Document'                => 'Group/Document/DoodiCouchdbGroupDocument.class.php',
    'Doodi_Couchdb_Group_View'                    => 'Group/View/DoodiCouchdbGroupView.class.php',
    'Doodi_Couchdb_Response'                      => 'Response/DoodiCouchdbResponse.class.php',
    'Doodi_Couchdb_Result_Set_Response'           => 'Result/Set/Response/DoodiCouchdbResultSetResponse.class.php',
    'Doodi_Couchdb_Status_Response'               => 'Status/Response/DoodiCouchdbStatusResponse.class.php',
    'Doodi_Couchdb_Stream_Connection'             => 'Stream/Connection/DoodiCouchdbStreamConnection.class.php',
    'Doodi_Couchdb_String_Validator'              => 'String/Validator/DoodiCouchdbStringValidator.class.php',
    'Doodi_Couchdb_Text_Validator'                => 'Text/Validator/DoodiCouchdbTextValidator.class.php',
    'Doodi_Couchdb_Tool_Multipart_Parser'         => 'Tool/Multipart/Parser/DoodiCouchdbToolMultipartParser.class.php',
    'Doodi_Couchdb_Tool_Multipart_Writer'         => 'Tool/Multipart/Writer/DoodiCouchdbToolMultipartWriter.class.php',
    'Doodi_Couchdb_Tool_String_Stream'            => 'Tool/String/Stream/DoodiCouchdbToolStringStream.class.php',
    'Doodi_Couchdb_User_Document'                 => 'User/Document/DoodiCouchdbUserDocument.class.php',
    'Doodi_Couchdb_User_File_View'                => 'User/File/View/DoodiCouchdbUserFileView.class.php',
    'Doodi_Couchdb_User_View'                     => 'User/View/DoodiCouchdbUserView.class.php',
    'Doodi_Couchdb_View'                          => 'View/DoodiCouchdbView.class.php',
    'Doodi_Couchdb_Array_Validator'               => 'Array/Validator/DoodiCouchdbArrayValidator.class.php',
    'Doodi_Couchdb_Date_Validator'                => 'Date/Validator/DoodiCouchdbDateValidator.class.php',
    'Doodi_Couchdb_Document_Validator'            => 'Document/Validator/DoodiCouchdbDocumentValidator.class.php',
    'Doodi_Couchdb_Email_Validator'               => 'Email/Validator/DoodiCouchdbEmailValidator.class.php',
    'Doodi_Couchdb_Exception'                     => 'Exception/DoodiCouchdbException.class.php',
    'Doodi_Couchdb_File_View'                     => 'File/View/DoodiCouchdbFileView.class.php',
    'Doodi_Couchdb_Float_Validator'               => 'Float/Validator/DoodiCouchdbFloatValidator.class.php',
    'Doodi_Couchdb_Image_File_Location_Validator' => 'Image/File/Location/Validator/DoodiCouchdbImageFileLocationValidator.class.php',
    'Doodi_Couchdb_Indexable_Date_Validator'      => 'Indexable/Date/Validator/DoodiCouchdbIndexableDateValidator.class.php',
    'Doodi_Couchdb_Integer_Validator'             => 'Integer/Validator/DoodiCouchdbIntegerValidator.class.php',
    'Doodi_Couchdb_No_Validator'                  => 'No/Validator/DoodiCouchdbNoValidator.class.php',
    'Doodi_Couchdb_Regexp_Validator'              => 'Regexp/Validator/DoodiCouchdbRegexpValidator.class.php',
    'Doodi_Couchdb_Response_Factory'              => 'Response/Factory/DoodiCouchdbResponseFactory.class.php',
    'Doodi_Couchdb_Tool'                          => 'Tool/DoodiCouchdbTool.class.php',
    'Doodi_Couchdb_Validator'                     => 'Validator/DoodiCouchdbValidator.class.php'
);

?>
