<?php

/**
 * This is an autogenerated routing table generated
 * by: FILENAME
 * at: DATE
 * for Doodi (DoozRs object oriented database interface)
 */
final class Doodi_Couchdb_Route
{
    public $matrix = array(
        '1290b6d9e63603623a0f6a70668d7fe0' => array(
            'class'       => 'phpillowCustomConnection',
            'method'      => 'createInstance',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '5b6b6c988143e37740d726bcea709337' => array(
            'class'       => 'phpillowConnection',
            'method'      => 'setOption',
            'type'        => 'static',
            'constructor' => true,
            'instance'    => null
        ),
        '20688322712ce589d262bc8ffb498a04' => array(
            'class'       => 'phpillowConnection',
            'method'      => 'setDatabase',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '622e7c8ea45cefc8f431f64654799f5e' => array(
            'class'       => 'phpillowConnection',
            'method'      => 'getDatabase',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'aebcb4b3693128deaa05a4e619b7fcb2' => array(
            'class'       => 'phpillowConnection',
            'method'      => 'getInstance',
            'type'        => 'static',
            'constructor' => true,
            'instance'    => null
        ),
        'd9b0c09ebb1d68f848abdfd2a98702f9' => array(
            'class'       => 'phpillowStreamConnection',
            'method'      => 'createInstance',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '0caca3f658933de33cefe2747c946267' => array(
            'class'       => 'phpillowConnection',
            'method'      => 'createInstance',
            'type'        => 'static',
            'constructor' => true,
            'instance'    => null
        ),
        '8cb9f6733828ccb31a3d081f28a7d77a' => array(
            'class'       => 'phpillowGroupDocument',
            'method'      => 'createNew',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '459aaa123f6fe04cd908c032faafca5d' => array(
            'class'       => 'phpillowDocument',
            'method'      => 'fetchById',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '23404a71724996a0cbfa7b47c3d394b9' => array(
            'class'       => 'phpillowDocument',
            'method'      => 'checkTypeOfResponse',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '298a9687b6c2182ae25f2e1e7292d4e6' => array(
            'class'       => 'phpillowDocument',
            'method'      => 'checkRequirements',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '55cff940ab691e2ad6ea53a09933ebf1' => array(
            'class'       => 'phpillowDocument',
            'method'      => 'save',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'ea59ec16680f91e8bb215781d6b514d8' => array(
            'class'       => 'phpillowDocument',
            'method'      => 'delete',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'd8461dcd228d04d18a317a0003dae556' => array(
            'class'       => 'phpillowDocument',
            'method'      => 'attachFile',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '8c1a46d4b0c25d5faf801335b126feae' => array(
            'class'       => 'phpillowDocument',
            'method'      => 'attachMemoryFile',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '4aa0999ace40070c0259b84aa41b3cb5' => array(
            'class'       => 'phpillowDocument',
            'method'      => 'getFile',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '40d00dbf507a1ebb092a8c5b8f30e27d' => array(
            'class'       => 'phpillowDocument',
            'method'      => 'getConnection',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '4c59b92ff58862bed653f3dfc83575ed' => array(
            'class'       => 'phpillowDocument',
            'method'      => 'setConnection',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '8a5234ac42024ebf3283eb376289fcf0' => array(
            'class'       => 'phpillowDocument',
            'method'      => 'getDatabase',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '23ec49bff1ae1fc4374e1eba05861e9f' => array(
            'class'       => 'phpillowDocument',
            'method'      => 'setDatabase',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '11022116b18c0809cb7b9689a4b3bb1d' => array(
            'class'       => 'phpillowUserDocument',
            'method'      => 'createNew',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '1e617594e0a2154a9178973f31fd2ce7' => array(
            'class'       => 'phpillowDocument',
            'method'      => 'createNew',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '6aa87bfd20273a1cbac78ecb09b4766b' => array(
            'class'       => 'phpillowException',
            'method'      => 'getText',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '21486eba761bb2003646a5752042f5ed' => array(
            'class'       => 'phpillowException',
            'method'      => 'getTextValues',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'ba0f69a7a6e69eeccf7759e1dd36465a' => array(
            'class'       => 'Exception',
            'method'      => 'getMessage',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '39b0c522ae9c13a600dc1df6d132ec6b' => array(
            'class'       => 'Exception',
            'method'      => 'getCode',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '24d1f1f538a325e13af05f498e033655' => array(
            'class'       => 'Exception',
            'method'      => 'getFile',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '0ce407144f72af1eb929121433a9d526' => array(
            'class'       => 'Exception',
            'method'      => 'getLine',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'cc24e6416cc9d537e68510f284b04e46' => array(
            'class'       => 'Exception',
            'method'      => 'getTrace',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '94cbf9d7ada5a9fc191bd269b921bdf7' => array(
            'class'       => 'Exception',
            'method'      => 'getPrevious',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'c7360eacb1c58d523bbcda36ebf26dab' => array(
            'class'       => 'Exception',
            'method'      => 'getTraceAsString',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '61113e3a67dd55ed17d1f5d1e11cce49' => array(
            'class'       => 'phpillowResponseErrorException',
            'method'      => 'getResponse',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'b0bbac2b072433ee89e029fc56430c29' => array(
            'class'       => 'phpillowUserFileView',
            'method'      => 'createNew',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '97d53858242b77f21ab4378ef028b784' => array(
            'class'       => 'phpillowFileView',
            'method'      => 'verifyView',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '54170f8484cfc623558bafca69531e41' => array(
            'class'       => 'phpillowView',
            'method'      => 'query',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '4392d9f641a61213be692e98191ed010' => array(
            'class'       => 'phpillowResponse',
            'method'      => 'getFullDocument',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '3dceaa2285e8dfcbc351556dc8b5f6ab' => array(
            'class'       => 'phpillowManager',
            'method'      => 'setViewClass',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '8d404e5591e867e05cf840ea8284ca85' => array(
            'class'       => 'phpillowManager',
            'method'      => 'getView',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'cb2fad25731969ecff34e8bc1a3d81d6' => array(
            'class'       => 'phpillowManager',
            'method'      => 'setDocumentClass',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '0ec0ae29196321c289af54550b7f0f2f' => array(
            'class'       => 'phpillowManager',
            'method'      => 'createDocument',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'd679e0b927a031c7be5fa5388ac2e1a0' => array(
            'class'       => 'phpillowManager',
            'method'      => 'fetchDocument',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '61cb3e2294a57abc5fcf9ae77b0d6e45' => array(
            'class'       => 'phpillowManager',
            'method'      => 'deleteDocument',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '1e30914a05a3532d928bb30ecb692249' => array(
            'class'       => 'phpillowResponseFactory',
            'method'      => 'parse',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '2c3f4969ec8c8086a6d674c878c27516' => array(
            'class'       => 'phpillowToolMultipartParser',
            'method'      => 'getDocument',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '86707e5e9c916f88848770eabd828edc' => array(
            'class'       => 'phpillowToolMultipartWriter',
            'method'      => 'writeDocument',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '5e962380e4b147b5da75456bac1bfef3' => array(
            'class'       => 'phpillowToolStringStream',
            'method'      => 'stream_open',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '5fcac7e70d5459273ce7e2ccea722b6d' => array(
            'class'       => 'phpillowToolStringStream',
            'method'      => 'stream_read',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '8bc42b04c31ad622e5a6a1a6bfe4e2f5' => array(
            'class'       => 'phpillowToolStringStream',
            'method'      => 'stream_write',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '2a7084c9e40948428a33201e6ee45720' => array(
            'class'       => 'phpillowToolStringStream',
            'method'      => 'stream_tell',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '7a2ad6065579652b1abf164e8a6661b0' => array(
            'class'       => 'phpillowToolStringStream',
            'method'      => 'stream_eof',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '6d31ef3abcb8683d26b4b28cc87321c4' => array(
            'class'       => 'phpillowToolStringStream',
            'method'      => 'stream_seek',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'a2786f790e8d1cc1daced78defebcb37' => array(
            'class'       => 'phpillowToolStringStream',
            'method'      => 'stream_stat',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '6c2af259783f93a989d7ee94a124f9aa' => array(
            'class'       => 'phpillowTool',
            'method'      => 'setOutputStreams',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '32e73eeb10cff6fe5a8b6385bad9cff1' => array(
            'class'       => 'phpillowTool',
            'method'      => 'dump',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'f1beef0bf410859a645eb912112b657f' => array(
            'class'       => 'phpillowTool',
            'method'      => 'load',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'd5ee02028b8aa441deb2c2dbf48b57bc' => array(
            'class'       => 'phpillowTool',
            'method'      => 'primeCaches',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '8c3993bd8e4f3d208871931c7bbf34d4' => array(
            'class'       => 'phpillowArrayValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '0eb5f4a24f14847eb6a3ae52eb04cb13' => array(
            'class'       => 'phpillowBooleanValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'b2f736082ec4b1d2f7ac33e0976d9622' => array(
            'class'       => 'phpillowDateValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'fb2ea276922330edb85066d1cec7224a' => array(
            'class'       => 'phpillowDocumentValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '143abe63d193ec587e5352c44ac991b2' => array(
            'class'       => 'phpillowDocumentArrayValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'cd1ac7c1af265d16782c5c572e206299' => array(
            'class'       => 'phpillowEmailValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '9291882e65144a243335a46efa3e8b01' => array(
            'class'       => 'phpillowFloatValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'a4af0db5a0f43f044f3c311ce61f6755' => array(
            'class'       => 'phpillowImageFileLocationValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'ee605031ff4a6e516900672ff6ff117e' => array(
            'class'       => 'phpillowIndexableDateValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'c67a2429de4a064cb80a97c4c5a5dea0' => array(
            'class'       => 'phpillowIntegerValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '289ac3e3758eaf5dc030c117716aca05' => array(
            'class'       => 'phpillowNoValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'f227937aed10b91e873916f0029b186a' => array(
            'class'       => 'phpillowNullValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'e65dc48df16281176e70c3918e952a24' => array(
            'class'       => 'phpillowObjectValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '24a083fa70b34ad1250cdd8bc57cb7a4' => array(
            'class'       => 'phpillowObjectArrayValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '56cbeef701344760f53cc9f0925c465c' => array(
            'class'       => 'phpillowOrValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'e2687a4f66e666b01ad3e1c7701147d0' => array(
            'class'       => 'phpillowRegexpValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '0cc39cd575acbcfbb6f7164398bd80e4' => array(
            'class'       => 'phpillowStringValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        'ca2f1e2452230fccd05a0dbdad9a5eff' => array(
            'class'       => 'phpillowTextValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '39c1f54335f04d7946600c8c59469317' => array(
            'class'       => 'phpillowUuidValidator',
            'method'      => 'validate',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '1049fcc40f2adb65d92d0feb736d31ba' => array(
            'class'       => 'phpillowGroupView',
            'method'      => 'createNew',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '3333e4d244aaad90bbfea6f6711c60de' => array(
            'class'       => 'phpillowView',
            'method'      => 'verifyView',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),
        '89adae1a651792724722ee3ddda20842' => array(
            'class'       => 'phpillowUserView',
            'method'      => 'createNew',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        )
    );
}

?>
