<?php

{{docblock.tpl}}

final class {{classname-route}}
{
    /**
     * This is an autogenerated routing table generated by: {{generator-filename}}
     * at: {{date}}
     * for: Doodi (DoozR's-object-oriented-database-interface)
     */
    public $matrix = array(
        {{route}}
    );
}

?>
