#!/usr/bin/php
<?php

if (php_sapi_name() != 'cli') {
    die('Must run from command line');
}


error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', 1);
ini_set('log_errors', 0);
ini_set('html_errors', 0);

require_once realpath(__DIR__ . '/../') . '/vendor/autoload.php';

// Force colors
\cli\Colors::enable();

\cli\line();
\cli\line(
    \cli\Colors::colorize('%N%n%1Console access prepared but not yet implemented. It took us some more time to get ready.')
);
