<?php

/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/**
 * DoozR - Doodi - Freezer - Model - Doodi - Route
 *
 * Route.php - Model - Doodi - Route
 *
 * PHP versions 5
 *
 * LICENSE:
 * DoozR - The PHP-Framework
 *
 * Copyright (c) 2005 - 2014, Benjamin Carl - All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 * - All advertising materials mentioning features or use of this software
 *   must display the following acknowledgement: This product includes software
 *   developed by Benjamin Carl and other contributors.
 * - Neither the name Benjamin Carl nor the names of other contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Please feel free to contact us via e-mail: opensource@clickalicious.de
 *
 * @category   DoozR
 * @package    DoozR_Model
 * @subpackage DoozR_Model_Doodi
 * @author     Benjamin Carl <opensource@clickalicious.de>
 * @copyright  2005 - 2014 Benjamin Carl
 * @license    http://www.opensource.org/licenses/bsd-license.php The BSD License
 * @version    Git: $Id$
 * @link       http://clickalicious.github.com/DoozR/
 * @see        -
 * @since      -
 */




/**
 * DoozR - Doodi - Freezer - Model - Doodi - Route
 *
 * Model - Doodi - Route
 *
 * @category   DoozR
 * @package    DoozR_Model
 * @subpackage DoozR_Model_Doodi
 * @author     Benjamin Carl <opensource@clickalicious.de>
 * @copyright  2005 - 2014 Benjamin Carl
 * @license    http://www.opensource.org/licenses/bsd-license.php The BSD License
 * @version    Git: $Id$
 * @link       http://clickalicious.github.com/DoozR/
 * @see        -
 * @since      -
 */

final class Model_Doodi_Route
{
    /**
     * This is an autogenerated routing table generated by: Generator.php
     * at: 2013-05-03 17:45:23
     * for: Doodi (DoozR's-object-oriented-database-interface)
     */
    public $matrix = array(

        '307e95f2061cb3d22ae2b21daba98425' => array(
            'class'       => 'Object_Freezer_Cache',
            'method'      => 'get',
            'type'        => 'instance',
            'constructor' => false,
            'instance'    => null
        ),

        'a8609f6c2f6ed48da61696c98f054d26' => array(
            'class'       => 'Object_Freezer_Cache',
            'method'      => 'put',
            'type'        => 'instance',
            'constructor' => false,
            'instance'    => null
        ),

        'cafc4b441b65e31d4e8a5a406c991744' => array(
            'class'       => 'Object_Freezer_HashGenerator_NonRecursiveSHA1',
            'method'      => 'getHash',
            'type'        => 'instance',
            'constructor' => false,
            'instance'    => null
        ),

        'd2c484cbf0cc5609bd0d81494f0210c2' => array(
            'class'       => 'Object_Freezer_IdGenerator_UUID',
            'method'      => 'getId',
            'type'        => 'instance',
            'constructor' => false,
            'instance'    => null
        ),

        '845c77bfdc8d0bc049a5a1e3b16875af' => array(
            'class'       => 'Object_Freezer_LazyProxy',
            'method'      => 'getObject',
            'type'        => 'instance',
            'constructor' => false,
            'instance'    => null
        ),

        'a0151706683392d388458a95ba4ab427' => array(
            'class'       => 'Object_Freezer_Storage_CouchDB',
            'method'      => 'send',
            'type'        => 'instance',
            'constructor' => false,
            'instance'    => null
        ),

        '32de99b9436647b6b6ec1798dec78444' => array(
            'class'       => 'Object_Freezer_Storage_CouchDB',
            'method'      => 'setDebug',
            'type'        => 'instance',
            'constructor' => false,
            'instance'    => null
        ),

        'e1b46169a6764edfe61c9035c1639255' => array(
            'class'       => 'Object_Freezer_Storage',
            'method'      => 'setUseLazyLoad',
            'type'        => 'instance',
            'constructor' => false,
            'instance'    => null
        ),

        'd1e4ba7eaa1e27dc5980221b89e160a1' => array(
            'class'       => 'Object_Freezer_Storage',
            'method'      => 'store',
            'type'        => 'instance',
            'constructor' => false,
            'instance'    => null
        ),

        '8bb53b3ffa4b6a4e5f762870f3d03a92' => array(
            'class'       => 'Object_Freezer_Storage',
            'method'      => 'fetch',
            'type'        => 'instance',
            'constructor' => false,
            'instance'    => null
        ),

        'fb40b8860a4a646cd99dd3392784d0a0' => array(
            'class'       => 'Object_Freezer_Util',
            'method'      => 'readAttributes',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),

        'b2819a03e1f032c56e7777b177bfcd42' => array(
            'class'       => 'Object_Freezer_Util',
            'method'      => 'getInvalidArgumentException',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),

        '5dd1fe8428fc307fc30bff224599f410' => array(
            'class'       => 'Object_Freezer',
            'method'      => 'freeze',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),

        '67868431806bb06094948181a5a74ac6' => array(
            'class'       => 'Object_Freezer',
            'method'      => 'thaw',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),

        '94d7598c7c2927186f45473631968762' => array(
            'class'       => 'Object_Freezer',
            'method'      => 'getIdGenerator',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),

        '83af336d9b21c5ac907f9c0263925d1b' => array(
            'class'       => 'Object_Freezer',
            'method'      => 'setIdGenerator',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),

        'ac0e39cacaf5c4ea8f3eec468aaa9294' => array(
            'class'       => 'Object_Freezer',
            'method'      => 'getHashGenerator',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),

        '498e5e3a705c77ff648b943cf5aabb98' => array(
            'class'       => 'Object_Freezer',
            'method'      => 'setHashGenerator',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),

        '7de106d1fa51fe8926c6050451a27398' => array(
            'class'       => 'Object_Freezer',
            'method'      => 'getBlacklist',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),

        '2c43ec758da684f44a9f852380de8c72' => array(
            'class'       => 'Object_Freezer',
            'method'      => 'setBlacklist',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),

        '0f0d1a4dabfb75e1967e1ecbec301383' => array(
            'class'       => 'Object_Freezer',
            'method'      => 'getUseAutoload',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),

        '963c6b2f8a9ff457d0796e64d6d802d6' => array(
            'class'       => 'Object_Freezer',
            'method'      => 'setUseAutoload',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),

        'ccf4f8d6a3d4af33c83533cb43ff1721' => array(
            'class'       => 'Object_Freezer',
            'method'      => 'isDirty',
            'type'        => 'static',
            'constructor' => false,
            'instance'    => null
        ),

    );
}
