at_currecny_major_long = Euro
at_currency_major_short = EUR
at_currency_minor_long = جزء من مائة دوِر؛  السنت؛  سنت
at_currency_minor_short = c
at_currency_major_symbol = €
at_currency_minor_symbol = ¢

de_currency_major_long = Euro
de_currency_major_short = EUR
de_currency_minor_long = جزء من مائة دوِر؛  السنت؛  سنت
de_currency_minor_short = c
de_currency_major_symbol = €
de_currency_minor_symbol = ¢

it_curreny_major_long = Euro
it_currency_major_short = EUR
it_currency_minor_long = جزء من مائة دوِر؛  السنت؛  سنت
it_currency_minor_short = c
it_currency_major_symbol = €
it_currency_minor_symbol = ¢

fr_currency_major_long = Euro
fr_currency_major_short = EUR
fr_currency_minor_long = جزء من مائة دوِر؛  السنت؛  سنت
fr_currency_minor_short = c
fr_currency_major_symbol = €
fr_currency_minor_symbol = ¢

es_currency_major_long = Euro
es_currency_major_short = EUR
es_currency_minor_long = جزء من مائة دوِر؛  السنت؛  سنت
es_currency_minor_short = c
es_currency_major_symbol = €
es_currency_minor_symbol = ¢

gb_currency_major_long = إجتاز؛  جرش
gb_currency_major_short = GBP
gb_currency_minor_long = بنس عملة
gb_currency_minor_short = p
gb_currency_major_symbol = £
gb_currency_minor_symbol = p

us_currency_major_long = دوِري العملة
us_currency_major_short = USD
us_currency_minor_long = جزء من مائة دوِر؛  السنت؛  سنت
us_currency_minor_short = c
us_currency_major_symbol = $
us_currency_minor_symbol = ¢

sa_currency_major_long = الدرهم؛  درهم
sa_currency_major_short = SAR
sa_currency_minor_long = Fils
sa_currency_minor_short =
sa_currency_major_symbol = SAR
sa_currency_minor_symbol =

ru_currency_major_long = Rubel
ru_currency_major_short = RUB
ru_currency_minor_long = Kopeken
ru_currency_minor_short =
ru_currency_major_symbol = RUB
ru_currency_minor_symbol = 